apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubecostguard
  labels:
    app.kubernetes.io/name: kubecostguard
    app.kubernetes.io/part-of: kubecostguard
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "services", "namespaces", "deployments", "replicasets", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]