apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubecostguard
  labels:
    app.kubernetes.io/name: kubecostguard
    app.kubernetes.io/part-of: kubecostguard
subjects:
  - kind: ServiceAccount
    name: kubecostguard
    namespace: kubecostguard
roleRef:
  kind: ClusterRole
  name: kubecostguard
  apiGroup: rbac.authorization.k8s.io