apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubecostguard
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - ingress.yaml