apiVersion: v1
kind: Secret
metadata:
  name: kubecostguard-secrets
  namespace: kubecostguard
  labels:
    app.kubernetes.io/name: kubecostguard
    app.kubernetes.io/part-of: kubecostguard
type: Opaque
data:
  # These are example values and should be replaced in production
  # Values are base64 encoded
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  GCP_SERVICE_ACCOUNT_JSON: ""
  AZURE_CLIENT_ID: ""
  AZURE_CLIENT_SECRET: ""
  JWT_SECRET: ""