kubernetes:
  kubeconfig: ""
  inCluster: true

health:
  scrapeIntervalSeconds: 60
  enabledCollectors:
    - node
    - pod
    - controlplane
  alertThresholds:
    cpuUtilizationPercent: 75
    memoryUtilizationPercent: 80
    podRestarts: 3

cost:
  updateIntervalMinutes: 15
  cloudProvider: "aws"  # Adjust based on your cloud provider
  pricingApiEndpoint: ""
  storageBackend: "postgres"
  storagePath: "host=prod-db.example.com port=5432 user=kubecost password=secret dbname=kubecost sslmode=require"

optimization:
  enableAutoScaling: true
  idleResourceThreshold: 0.2
  rightsizingThreshold: 0.6
  enableSpotRecommender: true
  minimumSavingsPercent: 20
  optimizationIntervalHours: 6
  applyRecommendations: true
  dryRun: false

api:
  port: 8443
  tlsEnabled: true
  tlsCertPath: "/etc/kubecostguard/tls/tls.crt"
  tlsKeyPath: "/etc/kubecostguard/tls/tls.key"
  authentication:
    enabled: true
    type: "jwt"
    jwtKey: "your-strong-jwt-secret-key-here"