apiVersion: v1
kind: Service
metadata:
  name: kubecostguard
  namespace: kubecostguard
spec:
  selector:
    app: kubecostguard
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP